#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x panel > /dev/null || panel &
~/.config/polybar/launch.sh

LAPTOP_MONITOR="LVDS"
HDMI_MONITOR="HDMI-0"

if xrandr -q | grep "$HDMI_MONITOR connected"; then
    xrandr --output "$HDMI_MONITOR" --auto --primary
    xrandr --output "$LAPTOP_MONITOR" --off
    bspc monitor "$HDMI_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
else
    xrandr --output "$LAPTOP_MONITOR" --auto --primary
    xrandr --output "$HDMI_MONITOR" --off
    bspc monitor "$LAPTOP_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
