#+author: who4mos
#+title: My dotfiles

* Emacs

This is my emacs config, it is not meant to work on any system, i'm using ~emacs 30.1~ at the moment.

** Requirements

There are a lot of packages required to build from source, in the next distro hopping session (or hopefully in a new computer) i'll write down all requirements. 

Besides that, the config requires:
- [[https://github.com/be5invis/Iosevka][Iosevka]] Font
- [[https://fonts.google.com/noto/specimen/Noto+Color+Emoji][Noto Color Emoji]] Font (emojis 🥳) 
- ~tree-sitter~
- ~cmake~, ~libtool~ and (optionally) ~libvterm~ (vterm)
- ~enchant~ and ~pkgconf~ (jinx)

** Building from source

Get the latest emacs version and install it:

#+begin_src sh
  git clone https://git.savannah.gnu.org/git/emacs.git
  ./autogen.sh
  ./configure --with-imagemagick --with-tree-sitter --with-native-compilation=aot
  make
  make install
#+end_src

Then create the emacs config folder:

#+begin_src sh
  mkdir -p ~/.config/emacs
#+end_src

Then open the [[file:emacs.org][emacs.org]] file in emacs and tangle it (~C-c C-v C-t~)!

** Language servers

- Python: [[https://microsoft.github.io/pyright/#/][pyright]]
- C: [[https://clang.llvm.org/extra/clangd.html][clangd]]
- Javascript: [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]]
- HTML and CSS: [[https://github.com/hrsh7th/vscode-langservers-extracted][vscode-langservers-extracted]]
- Java: [[https://github.com/eclipse/eclipse.jdt.ls][jdtls]]

** Spell Checkers

I'm using [[http://aspell.net/][aspell]] for english and [[https://github.com/hunspell/hunspell][hunspell]] for portuguese.

* BSPWM

[[https://github.com/baskerville/bspwm][bspwm]] is a window manager that represents windows as leaves of a full binary search tree.

The entire setup needs the following packages:
- ~bspwm~
- ~sxhkd~
- ~dmenu~
- ~polybar~

  
The bspwm configuration is stored in ~/.config/bspwm/bspwmrc~, you need to create that directory if it doesn't exist yet, link the ~bspwmrc~ script to the right location, and change its permissions:

#+begin_src sh
  mkdir -p ~/.config/bspwm
  ln -s ~/.dotfiles/bspwmrc ~/.config/bspwm/bspwmrc
  chmod +x ~/.config/bspwm/bspwmrc
#+end_src

** sxhkd

[[https://github.com/baskerville/sxhkd][sxhkd]] handles input for bspwm, the configuration file is stored in ~/.config/sxhkd/sxhkdrc~, you also need to create the directory and link the configuration file.

#+begin_src sh
  mkdir -p ~/.config/sxhkd
  ln -s ~/.dotfiles/sxhkdrc ~/.config/sxhkd/sxhkdrc
#+end_src

** polybar

[[https://github.com/polybar/polybar][polybar]] is an easy to configure status bar.

The *polybar* directory in this repo contains the configuration file ([[file:polybar/config.ini][config.ini]]) and the launch script ([[file:polybar/launch.sh][launch.sh]]) that is called inside BSPWM's config file. You need to link the directory to ~~/.config/polybar~ and change permissions to execute the script.

#+begin_src sh
  ln -s ~/.dotfiles/polybar ~/.config/polybar
  chmod +x ~/.config/polybar/launch.sh
#+end_src
